build:
  version: "1.0"

notificationService:
  message: "Welcome to Notification service microservice related prod APIs"
  contactDetails:
    name: "John Doe - Product Owner"
    email: "johnprod@budgetplanner.com"